// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $swapi_people from "./routes/swapi/people.tsx";
import * as $swapi_search from "./routes/swapi/search.tsx";
import * as $swapi_starships from "./routes/swapi/starships.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/swapi/people.tsx": $swapi_people,
    "./routes/swapi/search.tsx": $swapi_search,
    "./routes/swapi/starships.tsx": $swapi_starships,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
